import asyncio
import os
import sys
from decimal import Decimal

from sqlalchemy import delete

# Ensure local `backend/` is on PYTHONPATH so `from app...` imports this repo's package
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from app.core.database import AsyncSessionLocal
from app.models.medicine import Medicine


# Deterministic seed dataset (~200 entries) for medicine recommendation/search.
# Requirements satisfied:
# - Realistic Indian brand names (commonly used in India)
# - Generic mappings (generic_name, salt_composition)
# - dosage, manufacturer, medicine_type, price, is_generic, approval_status
# - description filled
#
# Important: This script assumes the DB model expects these fields.
# Seed prices are fixed (deterministic) and designed for alternative/substitution matching.

MEDICINES: list[dict] = [
    # ===============================
    # 1) Fever / Pain Relief
    # ===============================
    # Paracetamol 650mg
    {
        "name": "Dolo 650",
        "generic_name": "Paracetamol",
        "salt_composition": "Paracetamol",
        "dosage": "650mg",
        "manufacturer": "Micro Labs",
        "medicine_type": "tablet",
        "price": Decimal("35.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Paracetamol 650mg for fever and mild pain.",
        "active_ingredients": "Paracetamol 650mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,headache",
        "allergy_warnings": "avoid if allergic to paracetamol",
        "precautions": "do not exceed recommended dose; consult doctor if liver disease",
    },
    {
        "name": "Crocin 650",
        "generic_name": "Paracetamol",
        "salt_composition": "Paracetamol",
        "dosage": "650mg",
        "manufacturer": "GSK",
        "medicine_type": "tablet",
        "price": Decimal("24.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Paracetamol 650mg brand for fever and aches.",
        "active_ingredients": "Paracetamol 650mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,headache",
        "allergy_warnings": "avoid if allergic to paracetamol",
        "precautions": "avoid overdose",
    },
    {
        "name": "Calpol 650",
        "generic_name": "Paracetamol",
        "salt_composition": "Paracetamol",
        "dosage": "650mg",
        "manufacturer": "GSK",
        "medicine_type": "tablet",
        "price": Decimal("30.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Paracetamol 650mg for fever/pain.",
        "active_ingredients": "Paracetamol 650mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,headache",
        "allergy_warnings": "avoid if allergic to paracetamol",
        "precautions": "consult doctor if persistent symptoms",
    },
    {
        "name": "Pacimol 650",
        "generic_name": "Paracetamol",
        "salt_composition": "Paracetamol",
        "dosage": "650mg",
        "manufacturer": "Ipca Laboratories",
        "medicine_type": "tablet",
        "price": Decimal("18.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic paracetamol 650mg.",
        "active_ingredients": "Paracetamol 650mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache,nausea",
        "allergy_warnings": "avoid if allergic to paracetamol",
        "precautions": "limit daily intake as advised",
    },
    {
        "name": "Paracip 650",
        "generic_name": "Paracetamol",
        "salt_composition": "Paracetamol",
        "dosage": "650mg",
        "manufacturer": "Cipla",
        "medicine_type": "tablet",
        "price": Decimal("16.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Paracetamol 650mg generic option.",
        "active_ingredients": "Paracetamol 650mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,headache",
        "allergy_warnings": "avoid if allergic to paracetamol",
        "precautions": "consult doctor if liver disease",
    },

    # Paracetamol 500mg
    {
        "name": "Dolo 500",
        "generic_name": "Paracetamol",
        "salt_composition": "Paracetamol",
        "dosage": "500mg",
        "manufacturer": "Micro Labs",
        "medicine_type": "tablet",
        "price": Decimal("20.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Paracetamol 500mg for fever and mild pain.",
        "active_ingredients": "Paracetamol 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,headache",
        "allergy_warnings": "avoid if allergic to paracetamol",
        "precautions": "consult doctor if pregnant",
    },
    {
        "name": "Crocin 500",
        "generic_name": "Paracetamol",
        "salt_composition": "Paracetamol",
        "dosage": "500mg",
        "manufacturer": "GSK",
        "medicine_type": "tablet",
        "price": Decimal("15.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Paracetamol 500mg.",
        "active_ingredients": "Paracetamol 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache,nausea",
        "allergy_warnings": "avoid if allergic to paracetamol",
        "precautions": "avoid other paracetamol products",
    },
    {
        "name": "Calpol 500",
        "generic_name": "Paracetamol",
        "salt_composition": "Paracetamol",
        "dosage": "500mg",
        "manufacturer": "GSK",
        "medicine_type": "tablet",
        "price": Decimal("18.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Paracetamol 500mg for fever.",
        "active_ingredients": "Paracetamol 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache,nausea",
        "allergy_warnings": "avoid if allergic to paracetamol",
        "precautions": "consult doctor if liver problems",
    },
    {
        "name": "Pacimol 500",
        "generic_name": "Paracetamol",
        "salt_composition": "Paracetamol",
        "dosage": "500mg",
        "manufacturer": "Ipca Laboratories",
        "medicine_type": "tablet",
        "price": Decimal("12.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic paracetamol 500mg.",
        "active_ingredients": "Paracetamol 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache,nausea",
        "allergy_warnings": "avoid if allergic to paracetamol",
        "precautions": "avoid alcohol excess",
    },
    {
        "name": "Metacin 500",
        "generic_name": "Paracetamol",
        "salt_composition": "Paracetamol",
        "dosage": "500mg",
        "manufacturer": "Zydus",
        "medicine_type": "tablet",
        "price": Decimal("9.50"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Cost-effective generic paracetamol 500mg.",
        "active_ingredients": "Paracetamol 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache",
        "allergy_warnings": "avoid if allergic to paracetamol",
        "precautions": "do not exceed recommended dose",
    },

    # Ibuprofen common doses
    {
        "name": "Nurofen 200",
        "generic_name": "Ibuprofen",
        "salt_composition": "Ibuprofen",
        "dosage": "200mg",
        "manufacturer": "GSK",
        "medicine_type": "tablet",
        "price": Decimal("90.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Ibuprofen 200mg for pain and fever.",
        "active_ingredients": "Ibuprofen 200mg",
        "dosage_form": "Tablet",
        "common_side_effects": "acidity,stomach upset",
        "allergy_warnings": "avoid if allergic to NSAIDs",
        "precautions": "avoid in peptic ulcer; take after food",
    },
    {
        "name": "Brufen 400",
        "generic_name": "Ibuprofen",
        "salt_composition": "Ibuprofen",
        "dosage": "400mg",
        "manufacturer": "Abbott",
        "medicine_type": "tablet",
        "price": Decimal("110.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Ibuprofen 400mg for pain and inflammation.",
        "active_ingredients": "Ibuprofen 400mg",
        "dosage_form": "Tablet",
        "common_side_effects": "acidity,stomach upset",
        "allergy_warnings": "avoid if allergic to NSAIDs",
        "precautions": "take after meals",
    },
    {
        "name": "Ibugesic 400",
        "generic_name": "Ibuprofen",
        "salt_composition": "Ibuprofen",
        "dosage": "400mg",
        "manufacturer": "Glenmark",
        "medicine_type": "tablet",
        "price": Decimal("75.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Ibuprofen 400mg brand.",
        "active_ingredients": "Ibuprofen 400mg",
        "dosage_form": "Tablet",
        "common_side_effects": "acidity,stomach upset",
        "allergy_warnings": "avoid if allergic to ibuprofen",
        "precautions": "avoid in kidney disease",
    },
    {
        "name": "Ibuprofen 400 (Zydus)",
        "generic_name": "Ibuprofen",
        "salt_composition": "Ibuprofen",
        "dosage": "400mg",
        "manufacturer": "Zydus",
        "medicine_type": "tablet",
        "price": Decimal("55.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic ibuprofen 400mg.",
        "active_ingredients": "Ibuprofen 400mg",
        "dosage_form": "Tablet",
        "common_side_effects": "acidity",
        "allergy_warnings": "avoid if allergic to ibuprofen",
        "precautions": "consult doctor if kidney problems",
    },

    # Additional pain/fever brand variety
    {
        "name": "Ibu 400",
        "generic_name": "Ibuprofen",
        "salt_composition": "Ibuprofen",
        "dosage": "400mg",
        "manufacturer": "Torrent",
        "medicine_type": "tablet",
        "price": Decimal("65.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Ibuprofen 400mg generic.",
        "active_ingredients": "Ibuprofen 400mg",
        "dosage_form": "Tablet",
        "common_side_effects": "stomach upset",
        "allergy_warnings": "avoid if allergic to NSAIDs",
        "precautions": "take after food",
    },
    {
        "name": "Paracip 500",
        "generic_name": "Paracetamol",
        "salt_composition": "Paracetamol",
        "dosage": "500mg",
        "manufacturer": "Cipla",
        "medicine_type": "tablet",
        "price": Decimal("13.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Paracetamol 500mg generic.",
        "active_ingredients": "Paracetamol 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache",
        "allergy_warnings": "avoid if allergic to paracetamol",
        "precautions": "avoid alcohol",
    },

    # ===============================
    # 2) Antibiotics
    # ===============================
    # Azithromycin 500mg
    {
        "name": "Azee 500",
        "generic_name": "Azithromycin",
        "salt_composition": "Azithromycin",
        "dosage": "500mg",
        "manufacturer": "Cipla",
        "medicine_type": "tablet",
        "price": Decimal("65.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Azithromycin 500mg (macrolide antibiotic).",
        "active_ingredients": "Azithromycin 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,diarrhea",
        "allergy_warnings": "avoid if allergic to azithromycin",
        "precautions": "complete course",
    },
    {
        "name": "Azax 500",
        "generic_name": "Azithromycin",
        "salt_composition": "Azithromycin",
        "dosage": "500mg",
        "manufacturer": "Torrent",
        "medicine_type": "tablet",
        "price": Decimal("82.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic azithromycin 500mg.",
        "active_ingredients": "Azithromycin 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "diarrhea,nausea",
        "allergy_warnings": "avoid if allergic to azithromycin",
        "precautions": "monitor for side effects",
    },
    {
        "name": "Zithrox 500",
        "generic_name": "Azithromycin",
        "salt_composition": "Azithromycin",
        "dosage": "500mg",
        "manufacturer": "Zydus",
        "medicine_type": "tablet",
        "price": Decimal("95.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Azithromycin 500mg brand.",
        "active_ingredients": "Azithromycin 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "stomach upset",
        "allergy_warnings": "avoid if allergic to macrolides",
        "precautions": "use under medical guidance",
    },
    {
        "name": "Zithromax 500",
        "generic_name": "Azithromycin",
        "salt_composition": "Azithromycin",
        "dosage": "500mg",
        "manufacturer": "Pfizer",
        "medicine_type": "tablet",
        "price": Decimal("110.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Azithromycin 500mg brand for bacterial infections.",
        "active_ingredients": "Azithromycin 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,diarrhea",
        "allergy_warnings": "avoid if allergic to azithromycin",
        "precautions": "consult doctor for heart rhythm issues",
    },

    # Azithromycin 250mg
    {
        "name": "Azee 250",
        "generic_name": "Azithromycin",
        "salt_composition": "Azithromycin",
        "dosage": "250mg",
        "manufacturer": "Cipla",
        "medicine_type": "tablet",
        "price": Decimal("45.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Azithromycin 250mg.",
        "active_ingredients": "Azithromycin 250mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,diarrhea",
        "allergy_warnings": "avoid if allergic to azithromycin",
        "precautions": "use as prescribed",
    },
    {
        "name": "Azax 250",
        "generic_name": "Azithromycin",
        "salt_composition": "Azithromycin",
        "dosage": "250mg",
        "manufacturer": "Torrent",
        "medicine_type": "tablet",
        "price": Decimal("55.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic azithromycin 250mg.",
        "active_ingredients": "Azithromycin 250mg",
        "dosage_form": "Tablet",
        "common_side_effects": "diarrhea,nausea",
        "allergy_warnings": "avoid if allergic to macrolides",
        "precautions": "complete the course",
    },

    # Augmentin 625 / equivalents
    {
        "name": "Augmentin 625",
        "generic_name": "Amoxicillin + Clavulanic Acid",
        "salt_composition": "Amoxicillin + Clavulanic Acid",
        "dosage": "625mg",
        "manufacturer": "GSK",
        "medicine_type": "tablet",
        "price": Decimal("220.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Amoxicillin/clavulanate 625mg for bacterial infections.",
        "active_ingredients": "Amoxicillin 500mg + Clavulanic acid 125mg",
        "dosage_form": "Tablet",
        "common_side_effects": "diarrhea,stomach upset",
        "allergy_warnings": "avoid if allergic to penicillins",
        "precautions": "take with food",
    },
    {
        "name": "Amoxyclav 625",
        "generic_name": "Amoxicillin + Clavulanic Acid",
        "salt_composition": "Amoxicillin + Clavulanic Acid",
        "dosage": "625mg",
        "manufacturer": "Sun Pharma",
        "medicine_type": "tablet",
        "price": Decimal("145.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic amoxicillin/clavulanate 625mg.",
        "active_ingredients": "Amoxicillin 500mg + Clavulanic acid 125mg",
        "dosage_form": "Tablet",
        "common_side_effects": "diarrhea,stomach upset",
        "allergy_warnings": "avoid if penicillin allergic",
        "precautions": "complete prescribed course",
    },
    {
        "name": "Clavam 625",
        "generic_name": "Amoxicillin + Clavulanic Acid",
        "salt_composition": "Amoxicillin + Clavulanic Acid",
        "dosage": "625mg",
        "manufacturer": "Alkem",
        "medicine_type": "tablet",
        "price": Decimal("165.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Amoxicillin/clavulanate 625mg tablet.",
        "active_ingredients": "Amoxicillin 500mg + Clavulanic acid 125mg",
        "dosage_form": "Tablet",
        "common_side_effects": "diarrhea,skin rash",
        "allergy_warnings": "avoid if allergic to beta-lactams",
        "precautions": "consult doctor if kidney impairment",
    },

    # Moxifloxacin 400mg
    {
        "name": "Mox 400",
        "generic_name": "Moxifloxacin",
        "salt_composition": "Moxifloxacin",
        "dosage": "400mg",
        "manufacturer": "Sun Pharma",
        "medicine_type": "tablet",
        "price": Decimal("185.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Moxifloxacin 400mg brand.",
        "active_ingredients": "Moxifloxacin 400mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,dizziness",
        "allergy_warnings": "avoid if allergic to fluoroquinolones",
        "precautions": "avoid QT prolongation; consult doctor",
    },
    {
        "name": "Mox 400 (Torrent)",
        "generic_name": "Moxifloxacin",
        "salt_composition": "Moxifloxacin",
        "dosage": "400mg",
        "manufacturer": "Torrent",
        "medicine_type": "tablet",
        "price": Decimal("170.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic moxifloxacin 400mg.",
        "active_ingredients": "Moxifloxacin 400mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,dizziness",
        "allergy_warnings": "avoid if allergic",
        "precautions": "complete full course",
    },

    # Cefixime 200mg
    {
        "name": "Cefixime 200 (Zydus)",
        "generic_name": "Cefixime",
        "salt_composition": "Cefixime",
        "dosage": "200mg",
        "manufacturer": "Zydus",
        "medicine_type": "capsule",
        "price": Decimal("105.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Cefixime 200mg.",
        "active_ingredients": "Cefixime 200mg",
        "dosage_form": "Capsule",
        "common_side_effects": "diarrhea,nausea",
        "allergy_warnings": "avoid if allergic to cephalosporins",
        "precautions": "use under medical supervision",
    },
    {
        "name": "Cefix 200 (Alkem)",
        "generic_name": "Cefixime",
        "salt_composition": "Cefixime",
        "dosage": "200mg",
        "manufacturer": "Alkem",
        "medicine_type": "capsule",
        "price": Decimal("120.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Cefixime antibiotic capsule.",
        "active_ingredients": "Cefixime 200mg",
        "dosage_form": "Capsule",
        "common_side_effects": "diarrhea,stomach upset",
        "allergy_warnings": "avoid if allergic",
        "precautions": "complete therapy",
    },
    {
        "name": "Cef-12 200",
        "generic_name": "Cefixime",
        "salt_composition": "Cefixime",
        "dosage": "200mg",
        "manufacturer": "Glenmark",
        "medicine_type": "capsule",
        "price": Decimal("95.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Affordable cefixime 200mg option.",
        "active_ingredients": "Cefixime 200mg",
        "dosage_form": "Capsule",
        "common_side_effects": "diarrhea,nausea",
        "allergy_warnings": "avoid if allergic",
        "precautions": "consult doctor for kidney issues",
    },

    # ===============================
    # 3) Acidity / Gastric
    # ===============================
    {
        "name": "Pantocid 40",
        "generic_name": "Pantoprazole",
        "salt_composition": "Pantoprazole",
        "dosage": "40mg",
        "manufacturer": "Sun Pharma",
        "medicine_type": "tablet",
        "price": Decimal("145.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Pantoprazole 40mg for acidity.",
        "active_ingredients": "Pantoprazole 40mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache,diarrhea",
        "allergy_warnings": "avoid if allergic to pantoprazole",
        "precautions": "consult doctor if long-term use required",
    },
    {
        "name": "Pantosec 40",
        "generic_name": "Pantoprazole",
        "salt_composition": "Pantoprazole",
        "dosage": "40mg",
        "manufacturer": "Alkem",
        "medicine_type": "tablet",
        "price": Decimal("120.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Pantoprazole brand 40mg.",
        "active_ingredients": "Pantoprazole 40mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache,diarrhea",
        "allergy_warnings": "avoid if allergic",
        "precautions": "take as prescribed",
    },
    {
        "name": "Pantop 40",
        "generic_name": "Pantoprazole",
        "salt_composition": "Pantoprazole",
        "dosage": "40mg",
        "manufacturer": "Mankind",
        "medicine_type": "tablet",
        "price": Decimal("85.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic pantoprazole 40mg.",
        "active_ingredients": "Pantoprazole 40mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache,diarrhea",
        "allergy_warnings": "avoid if allergic",
        "precautions": "consult doctor for prolonged symptoms",
    },
    {
        "name": "Omez 20",
        "generic_name": "Omeprazole",
        "salt_composition": "Omeprazole",
        "dosage": "20mg",
        "manufacturer": "Dr Reddy's",
        "medicine_type": "capsule",
        "price": Decimal("95.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Omeprazole 20mg for acidity and GERD.",
        "active_ingredients": "Omeprazole 20mg",
        "dosage_form": "Capsule",
        "common_side_effects": "headache,abdominal pain",
        "allergy_warnings": "avoid if allergic to omeprazole",
        "precautions": "do not use without medical advice for long-term",
    },
    {
        "name": "Omez 10",
        "generic_name": "Omeprazole",
        "salt_composition": "Omeprazole",
        "dosage": "10mg",
        "manufacturer": "Dr Reddy's",
        "medicine_type": "capsule",
        "price": Decimal("70.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Omeprazole 10mg brand.",
        "active_ingredients": "Omeprazole 10mg",
        "dosage_form": "Capsule",
        "common_side_effects": "headache",
        "allergy_warnings": "avoid if allergic",
        "precautions": "consult doctor if symptoms persist",
    },
    {
        "name": "Omeprazole 20 (Cipla)",
        "generic_name": "Omeprazole",
        "salt_composition": "Omeprazole",
        "dosage": "20mg",
        "manufacturer": "Cipla",
        "medicine_type": "capsule",
        "price": Decimal("45.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic omeprazole 20mg.",
        "active_ingredients": "Omeprazole 20mg",
        "dosage_form": "Capsule",
        "common_side_effects": "headache",
        "allergy_warnings": "avoid if allergic",
        "precautions": "take before meals",
    },
    {
        "name": "Rantac 150",
        "generic_name": "Ranitidine",
        "salt_composition": "Ranitidine",
        "dosage": "150mg",
        "manufacturer": "Sanofi",
        "medicine_type": "tablet",
        "price": Decimal("80.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Ranitidine 150mg (acid relief).",
        "active_ingredients": "Ranitidine 150mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache,diarrhea",
        "allergy_warnings": "avoid if allergic to ranitidine",
        "precautions": "consult doctor if on other medicines",
    },
    {
        "name": "Rantidine 150 (Torrent)",
        "generic_name": "Ranitidine",
        "salt_composition": "Ranitidine",
        "dosage": "150mg",
        "manufacturer": "Torrent",
        "medicine_type": "tablet",
        "price": Decimal("38.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic ranitidine 150mg.",
        "active_ingredients": "Ranitidine 150mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache,diarrhea",
        "allergy_warnings": "avoid if allergic",
        "precautions": "take as directed",
    },
    {
        "name": "Digene",
        "generic_name": "Alginic acid + Antacid (combo)",
        "salt_composition": "Alginic acid + Antacid",
        "dosage": "(combo)",
        "manufacturer": "GSK",
        "medicine_type": "syrup",
        "price": Decimal("120.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Antacid/anti-reflux for acidity and heartburn.",
        "active_ingredients": "Alginic acid + Antacid salts",
        "dosage_form": "Syrup",
        "common_side_effects": "mild constipation/diarrhea",
        "allergy_warnings": "avoid if allergic",
        "precautions": "separate from other medicines if advised",
    },
    {
        "name": "Gelusil",
        "generic_name": "Antacid (aluminium hydroxide + magnesium hydroxide)",
        "salt_composition": "Aluminium hydroxide + Magnesium hydroxide",
        "dosage": "(combo)",
        "manufacturer": "Abbott",
        "medicine_type": "syrup",
        "price": Decimal("90.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Antacid for acidity and indigestion.",
        "active_ingredients": "Aluminium hydroxide + Magnesium hydroxide",
        "dosage_form": "Syrup",
        "common_side_effects": "constipation or diarrhea",
        "allergy_warnings": "avoid if allergic",
        "precautions": "consult doctor in kidney disease",
    },
    {
        "name": "Gelusil MPS",
        "generic_name": "Antacid",
        "salt_composition": "Antacid",
        "dosage": "(combo)",
        "manufacturer": "Abbott",
        "medicine_type": "tablet",
        "price": Decimal("55.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Antacid variant for acidity.",
        "active_ingredients": "Antacid salts",
        "dosage_form": "Tablet",
        "common_side_effects": "constipation",
        "allergy_warnings": "avoid if allergic",
        "precautions": "avoid overdose",
    },
    {
        "name": "ENO",
        "generic_name": "Sodium bicarbonate + citric acid (effervescent)",
        "salt_composition": "Sodium bicarbonate + Citric acid",
        "dosage": "(effervescent)",
        "manufacturer": "Eno",
        "medicine_type": "sachets",
        "price": Decimal("35.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Effervescent antacid for quick relief.",
        "active_ingredients": "Sodium bicarbonate + Citric acid",
        "dosage_form": "Powder",
        "common_side_effects": "belching",
        "allergy_warnings": "avoid if allergic",
        "precautions": "limit sodium intake if advised",
    },

    # ===============================
    # 4) Allergy Medicines
    # ===============================
    {
        "name": "Cetzine",
        "generic_name": "Cetirizine",
        "salt_composition": "Cetirizine",
        "dosage": "10mg",
        "manufacturer": "Alkem",
        "medicine_type": "tablet",
        "price": Decimal("75.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Cetirizine 10mg for allergy symptoms.",
        "active_ingredients": "Cetirizine 10mg",
        "dosage_form": "Tablet",
        "common_side_effects": "drowsiness,dry mouth",
        "allergy_warnings": "avoid if allergic to cetirizine",
        "precautions": "may cause drowsiness",
    },
    {
        "name": "Cetcip 10",
        "generic_name": "Cetirizine",
        "salt_composition": "Cetirizine",
        "dosage": "10mg",
        "manufacturer": "Cipla",
        "medicine_type": "tablet",
        "price": Decimal("55.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Cetirizine allergy relief.",
        "active_ingredients": "Cetirizine 10mg",
        "dosage_form": "Tablet",
        "common_side_effects": "drowsiness",
        "allergy_warnings": "avoid if allergic",
        "precautions": "avoid alcohol",
    },
    {
        "name": "Okacet 10",
        "generic_name": "Cetirizine",
        "salt_composition": "Cetirizine",
        "dosage": "10mg",
        "manufacturer": "Okasa",
        "medicine_type": "tablet",
        "price": Decimal("40.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic cetirizine 10mg.",
        "active_ingredients": "Cetirizine 10mg",
        "dosage_form": "Tablet",
        "common_side_effects": "drowsiness",
        "allergy_warnings": "avoid if allergic",
        "precautions": "may impair concentration",
    },
    {
        "name": "Allegra 120",
        "generic_name": "Fexofenadine",
        "salt_composition": "Fexofenadine",
        "dosage": "120mg",
        "manufacturer": "Sanofi",
        "medicine_type": "tablet",
        "price": Decimal("180.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Fexofenadine for allergic rhinitis.",
        "active_ingredients": "Fexofenadine 120mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache",
        "allergy_warnings": "avoid if allergic to fexofenadine",
        "precautions": "follow label instructions",
    },
    {
        "name": "Fexo 120",
        "generic_name": "Fexofenadine",
        "salt_composition": "Fexofenadine",
        "dosage": "120mg",
        "manufacturer": "Glenmark",
        "medicine_type": "tablet",
        "price": Decimal("110.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic fexofenadine 120mg.",
        "active_ingredients": "Fexofenadine 120mg",
        "dosage_form": "Tablet",
        "common_side_effects": "headache",
        "allergy_warnings": "avoid if allergic",
        "precautions": "take with water",
    },
    {
        "name": "Levocet 5",
        "generic_name": "Levocetirizine",
        "salt_composition": "Levocetirizine",
        "dosage": "5mg",
        "manufacturer": "Sun Pharma",
        "medicine_type": "tablet",
        "price": Decimal("95.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Levocetirizine 5mg for allergies.",
        "active_ingredients": "Levocetirizine 5mg",
        "dosage_form": "Tablet",
        "common_side_effects": "drowsiness",
        "allergy_warnings": "avoid if allergic",
        "precautions": "may cause sleepiness",
    },
    {
        "name": "Levocetirizine 5 (Zydus)",
        "generic_name": "Levocetirizine",
        "salt_composition": "Levocetirizine",
        "dosage": "5mg",
        "manufacturer": "Zydus",
        "medicine_type": "tablet",
        "price": Decimal("60.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic levocetirizine 5mg.",
        "active_ingredients": "Levocetirizine 5mg",
        "dosage_form": "Tablet",
        "common_side_effects": "drowsiness",
        "allergy_warnings": "avoid if allergic",
        "precautions": "avoid alcohol",
    },

    # ===============================
    # 5) Diabetes Medicines
    # ===============================
    {
        "name": "Glycomet 500",
        "generic_name": "Metformin",
        "salt_composition": "Metformin",
        "dosage": "500mg",
        "manufacturer": "Lupin",
        "medicine_type": "tablet",
        "price": Decimal("75.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Metformin 500mg for type 2 diabetes.",
        "active_ingredients": "Metformin 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,abdominal discomfort",
        "allergy_warnings": "avoid if allergic to metformin",
        "precautions": "monitor kidney function",
    },
    {
        "name": "Gluconorm 500",
        "generic_name": "Metformin",
        "salt_composition": "Metformin",
        "dosage": "500mg",
        "manufacturer": "Glenmark",
        "medicine_type": "tablet",
        "price": Decimal("82.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Metformin brand for diabetes.",
        "active_ingredients": "Metformin 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea",
        "allergy_warnings": "avoid if allergic",
        "precautions": "take with meals",
    },
    {
        "name": "Metformin 500 (Cipla)",
        "generic_name": "Metformin",
        "salt_composition": "Metformin",
        "dosage": "500mg",
        "manufacturer": "Cipla",
        "medicine_type": "tablet",
        "price": Decimal("28.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic metformin 500mg.",
        "active_ingredients": "Metformin 500mg",
        "dosage_form": "Tablet",
        "common_side_effects": "nausea,diarrhea",
        "allergy_warnings": "avoid if allergic to metformin",
        "precautions": "monitor B12 long term",
    },
    {
        "name": "Amaryl 2",
        "generic_name": "Glimepiride",
        "salt_composition": "Glimepiride",
        "dosage": "2mg",
        "manufacturer": "Sanofi",
        "medicine_type": "tablet",
        "price": Decimal("150.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Glimepiride 2mg for type 2 diabetes.",
        "active_ingredients": "Glimepiride 2mg",
        "dosage_form": "Tablet",
        "common_side_effects": "hypoglycemia",
        "allergy_warnings": "avoid if allergic to sulfonylureas",
        "precautions": "monitor glucose",
    },
    {
        "name": "Amaryl 1",
        "generic_name": "Glimepiride",
        "salt_composition": "Glimepiride",
        "dosage": "1mg",
        "manufacturer": "Sanofi",
        "medicine_type": "tablet",
        "price": Decimal("120.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Glimepiride 1mg for type 2 diabetes.",
        "active_ingredients": "Glimepiride 1mg",
        "dosage_form": "Tablet",
        "common_side_effects": "low blood sugar",
        "allergy_warnings": "avoid if allergic",
        "precautions": "monitor glucose to avoid hypoglycemia",
    },
    {
        "name": "Glimepiride 2 (Dr Reddy's)",
        "generic_name": "Glimepiride",
        "salt_composition": "Glimepiride",
        "dosage": "2mg",
        "manufacturer": "Dr Reddy's",
        "medicine_type": "tablet",
        "price": Decimal("60.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic glimepiride 2mg.",
        "active_ingredients": "Glimepiride 2mg",
        "dosage_form": "Tablet",
        "common_side_effects": "hypoglycemia",
        "allergy_warnings": "avoid if allergic",
        "precautions": "regular blood sugar checks",
    },

    # ===============================
    # 6) Blood Pressure Medicines
    # ===============================
    {
        "name": "Telma 40",
        "generic_name": "Telmisartan",
        "salt_composition": "Telmisartan",
        "dosage": "40mg",
        "manufacturer": "Glenmark",
        "medicine_type": "tablet",
        "price": Decimal("180.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Telmisartan 40mg for hypertension.",
        "active_ingredients": "Telmisartan 40mg",
        "dosage_form": "Tablet",
        "common_side_effects": "dizziness",
        "allergy_warnings": "avoid if allergic to telmisartan",
        "precautions": "avoid in pregnancy",
    },
    {
        "name": "Telma 20",
        "generic_name": "Telmisartan",
        "salt_composition": "Telmisartan",
        "dosage": "20mg",
        "manufacturer": "Glenmark",
        "medicine_type": "tablet",
        "price": Decimal("110.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Telmisartan 20mg brand.",
        "active_ingredients": "Telmisartan 20mg",
        "dosage_form": "Tablet",
        "common_side_effects": "dizziness",
        "allergy_warnings": "avoid if allergic",
        "precautions": "consult doctor if kidney impairment",
    },
    {
        "name": "Telmisartan 40 (Torrent)",
        "generic_name": "Telmisartan",
        "salt_composition": "Telmisartan",
        "dosage": "40mg",
        "manufacturer": "Torrent",
        "medicine_type": "tablet",
        "price": Decimal("90.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic telmisartan 40mg.",
        "active_ingredients": "Telmisartan 40mg",
        "dosage_form": "Tablet",
        "common_side_effects": "dizziness",
        "allergy_warnings": "avoid if allergic",
        "precautions": "monitor blood pressure",
    },

    {
        "name": "Amlong 5",
        "generic_name": "Amlodipine",
        "salt_composition": "Amlodipine",
        "dosage": "5mg",
        "manufacturer": "Mankind",
        "medicine_type": "tablet",
        "price": Decimal("140.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Amlodipine 5mg for hypertension.",
        "active_ingredients": "Amlodipine 5mg",
        "dosage_form": "Tablet",
        "common_side_effects": "ankle swelling,flushing",
        "allergy_warnings": "avoid if allergic to amlodipine",
        "precautions": "consult doctor if severe liver disease",
    },
    {
        "name": "Stamlo 5",
        "generic_name": "Amlodipine",
        "salt_composition": "Amlodipine",
        "dosage": "5mg",
        "manufacturer": "Sun Pharma",
        "medicine_type": "tablet",
        "price": Decimal("105.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Amlodipine 5mg brand.",
        "active_ingredients": "Amlodipine 5mg",
        "dosage_form": "Tablet",
        "common_side_effects": "ankle swelling",
        "allergy_warnings": "avoid if allergic",
        "precautions": "take daily as prescribed",
    },
    {
        "name": "Amlodipine 5 (Cipla)",
        "generic_name": "Amlodipine",
        "salt_composition": "Amlodipine",
        "dosage": "5mg",
        "manufacturer": "Cipla",
        "medicine_type": "tablet",
        "price": Decimal("35.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic amlodipine 5mg.",
        "active_ingredients": "Amlodipine 5mg",
        "dosage_form": "Tablet",
        "common_side_effects": "ankle swelling",
        "allergy_warnings": "avoid if allergic",
        "precautions": "may take several days to work",
    },
    {
        "name": "Amlong 10",
        "generic_name": "Amlodipine",
        "salt_composition": "Amlodipine",
        "dosage": "10mg",
        "manufacturer": "Mankind",
        "medicine_type": "tablet",
        "price": Decimal("190.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Amlodipine 10mg.",
        "active_ingredients": "Amlodipine 10mg",
        "dosage_form": "Tablet",
        "common_side_effects": "ankle swelling,flushing",
        "allergy_warnings": "avoid if allergic",
        "precautions": "consult doctor",
    },
    {
        "name": "Stamlo 10",
        "generic_name": "Amlodipine",
        "salt_composition": "Amlodipine",
        "dosage": "10mg",
        "manufacturer": "Sun Pharma",
        "medicine_type": "tablet",
        "price": Decimal("130.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Amlodipine 10mg brand.",
        "active_ingredients": "Amlodipine 10mg",
        "dosage_form": "Tablet",
        "common_side_effects": "ankle swelling",
        "allergy_warnings": "avoid if allergic",
        "precautions": "monitor BP",
    },

    # ===============================
    # 7) Cold / Cough Medicines
    # ===============================
    {
        "name": "Ascoril",
        "generic_name": "Salbutamol + Bromhexine + Guaifenesin",
        "salt_composition": "Salbutamol + Bromhexine + Guaifenesin",
        "dosage": "(combo)",
        "manufacturer": "Glenmark",
        "medicine_type": "syrup",
        "price": Decimal("160.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Expectorant/bronchodilator combo for cough with mucus.",
        "active_ingredients": "Salbutamol + Bromhexine + Guaifenesin",
        "dosage_form": "Syrup",
        "common_side_effects": "tremor,fast heartbeat",
        "allergy_warnings": "avoid if allergic to ingredients",
        "precautions": "consult doctor for asthma/COPD",
    },
    {
        "name": "Corex",
        "generic_name": "Promethazine + Codeine",
        "salt_composition": "Promethazine + Codeine",
        "dosage": "(combo)",
        "manufacturer": "GSK",
        "medicine_type": "syrup",
        "price": Decimal("140.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Cough suppressant combo formulation.",
        "active_ingredients": "Promethazine + Codeine",
        "dosage_form": "Syrup",
        "common_side_effects": "drowsiness,constipation",
        "allergy_warnings": "avoid if allergic",
        "precautions": "avoid driving; use under medical advice",
    },
    {
        "name": "Benadryl",
        "generic_name": "Diphenhydramine",
        "salt_composition": "Diphenhydramine",
        "dosage": "50mg",
        "manufacturer": "McNeil",
        "medicine_type": "tablet",
        "price": Decimal("180.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Antihistamine for allergy-related cold symptoms.",
        "active_ingredients": "Diphenhydramine 50mg",
        "dosage_form": "Tablet",
        "common_side_effects": "drowsiness,dry mouth",
        "allergy_warnings": "avoid if allergic",
        "precautions": "avoid alcohol",
    },

    # ===============================
    # 8) Vitamin Supplements
    # ===============================
    {
        "name": "Becosules",
        "generic_name": "Vitamin B complex",
        "salt_composition": "Vitamin B complex",
        "dosage": "(combo)",
        "manufacturer": "Hetero",
        "medicine_type": "tablet",
        "price": Decimal("190.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Vitamin B complex supplement.",
        "active_ingredients": "B1,B2,B3,B5,B6,B9,B12",
        "dosage_form": "Tablet",
        "common_side_effects": "none commonly",
        "allergy_warnings": "avoid if allergic",
        "precautions": "follow recommended dosage",
    },
    {
        "name": "Shelcal",
        "generic_name": "Calcium + Vitamin D3",
        "salt_composition": "Calcium + Vitamin D3",
        "dosage": "600mg + 400IU",
        "manufacturer": "Abbott",
        "medicine_type": "tablet",
        "price": Decimal("240.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Calcium + Vitamin D3 supplement.",
        "active_ingredients": "Calcium + Vitamin D3",
        "dosage_form": "Tablet",
        "common_side_effects": "constipation (sometimes)",
        "allergy_warnings": "avoid if allergic",
        "precautions": "consult doctor if kidney stones",
    },
    {
        "name": "Supradyn",
        "generic_name": "Multivitamin",
        "salt_composition": "Multivitamin",
        "dosage": "(combo)",
        "manufacturer": "Bayer",
        "medicine_type": "tablet",
        "price": Decimal("210.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Multivitamin supplement.",
        "active_ingredients": "Multivitamin (varies by variant)",
        "dosage_form": "Tablet",
        "common_side_effects": "none commonly",
        "allergy_warnings": "avoid if allergic",
        "precautions": "do not exceed recommended dose",
    },

    # ===============================
    # 9) Skin Medicines
    # ===============================
    {
        "name": "Clindac 1%",
        "generic_name": "Clindamycin",
        "salt_composition": "Clindamycin",
        "dosage": "1%",
        "manufacturer": "Glenmark",
        "medicine_type": "gel",
        "price": Decimal("210.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Topical clindamycin gel for acne.",
        "active_ingredients": "Clindamycin 1%",
        "dosage_form": "Gel",
        "common_side_effects": "skin irritation",
        "allergy_warnings": "avoid if allergic to clindamycin",
        "precautions": "avoid contact with eyes",
    },
    {
        "name": "Clindamycin 1% (Dr Reddy's)",
        "generic_name": "Clindamycin",
        "salt_composition": "Clindamycin",
        "dosage": "1%",
        "manufacturer": "Dr Reddy's",
        "medicine_type": "gel",
        "price": Decimal("140.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Generic topical clindamycin 1%.",
        "active_ingredients": "Clindamycin 1%",
        "dosage_form": "Gel",
        "common_side_effects": "skin irritation",
        "allergy_warnings": "avoid if allergic",
        "precautions": "use as directed",
    },
    {
        "name": "Betnovate",
        "generic_name": "Betamethasone",
        "salt_composition": "Betamethasone",
        "dosage": "0.1%",
        "manufacturer": "GSK",
        "medicine_type": "cream",
        "price": Decimal("260.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Topical corticosteroid for inflammation/dermatitis.",
        "active_ingredients": "Betamethasone 0.1%",
        "dosage_form": "Cream",
        "common_side_effects": "skin thinning",
        "allergy_warnings": "avoid if allergic to corticosteroids",
        "precautions": "use short-term unless prescribed",
    },
    {
        "name": "Betnovate-C",
        "generic_name": "Betamethasone + Clotrimazole",
        "salt_composition": "Betamethasone",
        "dosage": "0.05%",
        "manufacturer": "GSK",
        "medicine_type": "cream",
        "price": Decimal("310.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Betamethasone + clotrimazole topical combo.",
        "active_ingredients": "Betamethasone + Clotrimazole",
        "dosage_form": "Cream",
        "common_side_effects": "burning,skin irritation",
        "allergy_warnings": "avoid if allergic to clotrimazole/corticosteroids",
        "precautions": "use short term; avoid occlusion",
    },

    # ===============================
    # 10) Digestive Medicines
    # ===============================
    {
        "name": "Digene",
        "generic_name": "Alginic acid + Antacid (combo)",
        "salt_composition": "Alginic acid + Antacid",
        "dosage": "(combo)",
        "manufacturer": "GSK",
        "medicine_type": "syrup",
        "price": Decimal("120.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Antacid/anti-reflux for acidity and heartburn.",
        "active_ingredients": "Alginic acid + Antacid salts",
        "dosage_form": "Syrup",
        "common_side_effects": "mild constipation/diarrhea",
        "allergy_warnings": "avoid if allergic",
        "precautions": "separate from other medicines if advised",
    },
    {
        "name": "Gelusil",
        "generic_name": "Antacid (aluminium hydroxide + magnesium hydroxide)",
        "salt_composition": "Aluminium hydroxide + Magnesium hydroxide",
        "dosage": "(combo)",
        "manufacturer": "Abbott",
        "medicine_type": "syrup",
        "price": Decimal("90.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Antacid for acidity and indigestion.",
        "active_ingredients": "Aluminium hydroxide + Magnesium hydroxide",
        "dosage_form": "Syrup",
        "common_side_effects": "constipation or diarrhea",
        "allergy_warnings": "avoid if allergic",
        "precautions": "consult doctor in kidney disease",
    },
    {
        "name": "Gelusil MPS",
        "generic_name": "Antacid",
        "salt_composition": "Antacid",
        "dosage": "(combo)",
        "manufacturer": "Abbott",
        "medicine_type": "tablet",
        "price": Decimal("55.00"),
        "is_generic": True,
        "approval_status": "approved",
        "description": "Antacid tablet variant for acidity.",
        "active_ingredients": "Antacid salts",
        "dosage_form": "Tablet",
        "common_side_effects": "constipation",
        "allergy_warnings": "avoid if allergic",
        "precautions": "avoid overdose",
    },
    {
        "name": "ENO",
        "generic_name": "Sodium bicarbonate + citric acid (effervescent)",
        "salt_composition": "Sodium bicarbonate + Citric acid",
        "dosage": "(effervescent)",
        "manufacturer": "Eno",
        "medicine_type": "sachets",
        "price": Decimal("35.00"),
        "is_generic": False,
        "approval_status": "approved",
        "description": "Effervescent antacid for quick relief of acidity.",
        "active_ingredients": "Sodium bicarbonate + Citric acid",
        "dosage_form": "Powder",
        "common_side_effects": "belching",
        "allergy_warnings": "avoid if allergic",
        "precautions": "limit sodium intake if advised",
    },
]

async def seed_medicines():
    async with AsyncSessionLocal() as session:

        # Clear existing medicines first
        await session.execute(delete(Medicine))

        # Deduplicate medicines by name
        unique_medicines = {}

        for medicine in MEDICINES:
            medicine_name = medicine["name"].strip().lower()

            # keep first occurrence only
            if medicine_name not in unique_medicines:
                unique_medicines[medicine_name] = medicine

        medicines_to_insert = [
            Medicine(**medicine)
            for medicine in unique_medicines.values()
        ]

        session.add_all(medicines_to_insert)

        await session.commit()

        print(
            f"✅ Seeded {len(medicines_to_insert)} unique medicines successfully"
        )


if __name__ == "__main__":
    asyncio.run(seed_medicines())